import { DossierData } from './localStorage';
import { defaultClientData } from '../context/OnboardingContext';

export function createDemoDossiers(): DossierData[] {
  return [
    {
      id: 'demo_1',
      clientData: {
        ...defaultClientData,
        siren: '732829320',
        nom: 'Martin Dupont',
        email: 'martin.dupont@sarl-dupont.fr',
        telephone: '0612345678',
        missionType: 'reprise',
        confrereEmail: 'cabinet.ancien@expert-comptable.fr',
        raisonSociale: 'SARL DUPONT & ASSOCIÉS',
        siret: '73282932000017',
        formeJuridique: 'Société à responsabilité limitée',
        codeNAF: '6920Z',
        libelleNAF: 'Activités comptables',
        adresse: '47 Rue des Comptables',
        codePostal: '75008',
        ville: 'Paris',
        capital: '50 000 €',
        dateCreation: '2018-03-15',
        effectif: '10 à 19',
        documentDemandeSent: true,
        sharepointUploadLink: 'https://cabinet.sharepoint.com/:f:/g/clients/depot/732829320',
        sharepointFolderUrl: 'https://cabinet.sharepoint.com/sites/clients/DUPONT',
      },
      stepStatuses: ['completed', 'completed', 'completed', 'active', 'pending', 'pending', 'pending', 'pending', 'pending', 'pending', 'pending'],
      currentStep: 4,
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'demo_2',
      clientData: {
        ...defaultClientData,
        siren: '123456782',
        nom: 'Sophie Martin',
        email: 'sophie.martin@startup-martin.fr',
        telephone: '0698765432',
        missionType: 'creation',
        raisonSociale: 'MARTIN INNOVATION SAS',
        siret: '12345678200015',
        formeJuridique: 'Société par actions simplifiée',
        codeNAF: '6201Z',
        libelleNAF: 'Programmation informatique',
        adresse: '12 Avenue de la Tech',
        codePostal: '69003',
        ville: 'Lyon',
        capital: '100 000 €',
        dateCreation: '2024-01-10',
        effectif: '3 à 5',
        documentDemandeSent: true,
        sharepointUploadLink: 'https://cabinet.sharepoint.com/:f:/g/clients/depot/123456782',
        // Champs spécifiques création
        formeJuridiqueCreation: 'SAS',
        capitalCreation: '10000',
        activiteCreation: 'Développement de logiciels et conseil en stratégie digitale',
        denominationCreation: 'MARTIN INNOVATION SAS',
        mandatCreationEnvoye: true,
        mandatCreationSigne: true,
      },
      stepStatuses: ['completed', 'completed', 'completed', 'completed', 'skipped', 'completed', 'active', 'pending', 'pending', 'pending', 'pending'],
      currentStep: 7,
      createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'demo_3',
      clientData: {
        ...defaultClientData,
        siren: '987654321',
        nom: 'Jean Legrand',
        email: 'contact@legrand-consulting.fr',
        telephone: '0623456789',
        missionType: 'reprise',
        confrereEmail: 'ancien@cabinet.fr',
        raisonSociale: 'LEGRAND CONSULTING SARL',
        siret: '98765432100012',
        formeJuridique: 'Société à responsabilité limitée',
        codeNAF: '7022Z',
        libelleNAF: 'Conseil pour les affaires et autres conseils de gestion',
        adresse: '33 Boulevard du Commerce',
        codePostal: '13001',
        ville: 'Marseille',
        capital: '25 000 €',
        dateCreation: '2015-06-20',
        effectif: '6 à 9',
      },
      stepStatuses: ['completed', 'active', 'pending', 'pending', 'pending', 'pending', 'pending', 'pending', 'pending', 'pending', 'pending'],
      currentStep: 2,
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
  ];
}